player_name = "Tesseract"
combat_class = "Techno-Mage"
class_level = 1
weapon_type = "Lv.1 Server Staff"
sheild_type = "Lv.1 Terminal Tome"
familiar = "Rock Crab"
electro-mana_total = 1000
hitpoint_total = 500
spell_library_capacity = 4
hours_played = 1.5
kilometers_traveled = 46.7
damage_dealt = 2343.9
damage_taken = 1001.7
completed_tutorial = true
started_main_quest_line = false
member_of_a_guild = false
familiar_acqired = true